scripts/deploy.sh

- Closes #10 
1. 내용
- deploy.sh 스크립트 수정
- CD 과정을 보면 아래와 같습니다.
``` java
1. CD yml 파일이 실행이 되면 main 브랜치에 있는 코드들 기준으로 프로젝트를 build 한 다음에
1. build 결과로 생긴 jar 파일
2. appspec.yml 파일
3. scripts 내에 있는 sh 파일
이 3개를 zip 파일로 묶어서 s3로 보낸다.
2. Code Deploy는 통해서 s3에 올라간 zip 파일 중 appspec.yml 파일을 확인해서 배포를 진행한다.
3. ec2 `/home/ubuntu/app` 경로에 zip 파일 내에 있는 파일들을 전송하고, zip 파일 내에 있었던 deploy.sh를 실행한다.
```
하지만 지금까지 /build/libs/SNAPSHOT 이 경로에 있는 jar 파일을 실행 중이었기 때문에 최신 jar 파일을 실행하지 못했습니다.
그래서 build path를 수정해서 최신 jar 파일이 있는 경로를 지정해줬습니다.

#10 [fix] deploy.sh 스크립트 수정

---

src/main/java/com/asap/server/common/advice/ControllerExceptionAdvice.java
src/main/java/com/asap/server/config/WebConfig.java
src/main/java/com/asap/server/controller/dto/request/AvailableTimeRequestDto.java
src/main/java/com/asap/server/controller/dto/request/MeetingSaveRequestDto.java
src/main/java/com/asap/server/controller/dto/request/PreferTimeSaveRequestDto.java
src/main/java/com/asap/server/controller/dto/request/UserMeetingTimeSaveRequestDto.java
src/main/java/com/asap/server/domain/enums/Duration.java
src/main/java/com/asap/server/domain/enums/Place.java
src/main/java/com/asap/server/domain/enums/TimeSlot.java
src/main/java/com/asap/server/exception/Error.java

- Closes #57 
1. request error 처리 + 404 에러 핸들링
- jsoncreator 어노테이션으로 enum 유효성 검사하는 로직으로 만약 enum에 존재하지 않는 값을 받으면 400에러 던져주었습니다.

#57 [feat] request error 처리 + 404 에러 핸들링

---

src/main/java/com/asap/server/common/utils/DayOfWeekConverter.java
src/main/java/com/asap/server/controller/MeetingController.java
src/main/java/com/asap/server/controller/dto/response/FixedMeetingResponseDto.java
src/main/java/com/asap/server/domain/ConfirmedDateTime.java
src/main/java/com/asap/server/domain/Meeting.java
src/main/java/com/asap/server/domain/Place.java
src/main/java/com/asap/server/exception/model/AsapException.java
src/main/java/com/asap/server/exception/model/BadRequestException.java
src/main/java/com/asap/server/service/MeetingService.java

- Closes #111 
1. 내용
- 큐카드 API 수정
- Get Api 큐카드 가져올 때 userId 가 필요 없기도 하고, 이미 적용하고 있지 않은데 swagger에 401 이런거 있길래 삭제했습니다. 노션에도 해당 API `isToken` 체크 해제했습니다~
-  `@Getter` 수정
- LocalDateTime 을 통해 response 값 추출

#111 [fix] 큐카드 API 수정

---

src/main/java/com/asap/server/common/utils/PasswordEncryptionUtil.java
src/main/java/com/asap/server/domain/Meeting.java
src/main/java/com/asap/server/domain/PasswordInfo.java
src/main/java/com/asap/server/service/MeetingService.java
src/main/java/com/asap/server/service/UserService.java
src/main/java/com/asap/server/service/vo/PasswordInfoVo.java
src/test/java/com/asap/server/common/utils/PasswordEncryptionUtilTest.java

- Closes #168 
1. 내용
- 비밀번호 암호화 Util 함수 구현
- 회의 생성 api 내에 함수화 로직 적용
- 방장 로그인 api 내에 함수화 로직 적용
- [해당 블로그](https://st-lab.tistory.com/100) 참고 하면서 작업했습니다.
- 비밀번호에 소금 치면 더욱 암호화가 잘 될 것이라 기대되기에 table 내에 회의의 salt 를 저장하는 속성을 추가했습니다..!

#168 [feat] 비밀번호 암호화 구현

---

src/main/java/com/asap/server/common/utils/BestMeetingUtil.java
src/main/java/com/asap/server/domain/enums/TimeSlot.java
src/test/java/com/asap/server/common/utils/GetBestMeetingTimeTest.java
src/test/java/com/asap/server/common/utils/SearchBestMeetingTest.java

- Closes #193 
1. 내용
- 최적의 회의시간 도출 로직 수정
time block 이 "09:00" 일 땐 09:00 ~ 09:30 인 것을 적용한 로직 입니다.

#193 [feat] 최적의 회의시간 도출 로직 수정

---

src/main/java/com/asap/server/config/resolver/user/UserIdResolver.java

- Closes #199 
1. 내용
- "Bearer " 만 들어왔을 때 split[1] 을 했을 시 null point exception 으로 인한 500 에러를 막기 위한 로직입니다. 
-

#199 [fix] user id 인증 방식 개선

---

src/main/java/com/asap/server/common/aspect/LoggingAspect.java
src/main/java/com/asap/server/common/filter/CustomServletWrappingFilter.java
src/main/java/com/asap/server/config/filter/HttpRequestConfig.java

- Closes #207 
1. `CustomServletWrappingFilter` : spring-web에 구현되어있는 ContentCachingRequestWrapper를 사용해서 filter에서 Wrapperclass로 전환 ->  Wrapper 클래스를 사용하면 response가 클라이언트에 전송이 안되기 때문에 `responseWrapper.copyBodyToResponse();`를 적어주었습니다!
2. `HttpRequestConfig` : 위에 커스텀해준 필터를 등록
원래 로깅되던 방식에서 2번째 줄 추가 되었습니다
``` 
[2023-09-30 10:02:44:10929] [http-nio-8080-exec-2] INFO  [com.asap.server.common.aspect.LoggingAspect.requestLogging:38] - ====> Request: POST http://localhost:8080/meeting (167ms)
*Header = {authorization=, content-length=325, postman-token=7e43bd56-e26d-42c2-a3a1-b52eb9229bf3, host=localhost:8080, content-type=application/json, connection=keep-alive, cache-control=no-cache, accept-encoding=gzip, deflate, br, user-agent=PostmanRuntime/7.33.0, accept=*/*}
[2023-09-30 10:02:44:10931] …
```

#207 [feat] request body 로깅 적용

---

src/main/java/com/asap/server/controller/UserController.java

- Closes #196 
1. 방장 회의 가능시간의 경우 List<Dto> 형식으로 받는건데 List안에 null 값이 넘어올 경우를 예외 처리 해놓지 않았더라고요! 그래서 했습니다! 간단한 문제였네요!
- 로그 짱!!

#196 [fix] 방장 회의 가능 시간 입력 넘어오지 않았을 때 에러 처리

---

src/main/java/com/asap/server/repository/AvailableDateRepository.java
src/main/java/com/asap/server/repository/PreferTimeRepository.java
src/main/java/com/asap/server/repository/TimeBlockRepository.java
src/main/java/com/asap/server/repository/TimeBlockUserRepository.java
src/main/java/com/asap/server/service/AvailableDateService.java
src/main/java/com/asap/server/service/MeetingService.java
src/main/java/com/asap/server/service/PreferTimeService.java
src/main/java/com/asap/server/service/TimeBlockService.java
src/main/java/com/asap/server/service/TimeBlockUserService.java

- Closes #208 
1. 내용
- 회의 확정 후 불필요한 데이터 삭제 로직 구현
- PreferTime , AvailableDate , TimeBlock, TimeBlockUser 데이터를 삭제했습니다.

#208 [feat] 회의 확정 후 불필요한 데이터 삭제 로직 구현

---

src/main/java/com/asap/server/domain/User.java
src/main/java/com/asap/server/repository/UserRepository.java
src/main/java/com/asap/server/service/MeetingService.java
src/main/java/com/asap/server/service/UserService.java

- Closes #216 
1. 내용
- user is_fixed update 로직 개선
- 이전에는 user 한명 한명 select 를 한뒤 한명 한명 update 를 하는 방식이었습니다. 
그래서 [ (확정된 user의 수) * (2) ] 번의 쿼리가 실행되었습니다.
- 그래서 `in` 명령어를 활용해서 request 로 온 userId 에 포함한 user 만 update 하도록 개선했습니다.
결과적으로 하나의 쿼리만 나가도록 했습니다.
실제로 유저가 10명일 때 회의 확정 속도를 테스트 했을 때 
이전의 방식은 평균 169.2ms 걸렸지만
개선 후 방식은 평균 107.4ms 로 쿼리 속도가 다소 줄어든 것을 확인할 수 있었습니다.

#216 [feat] user is_fixed update 로직 개선

---

src/main/java/com/asap/server/service/MeetingService.java
src/main/java/com/asap/server/service/PreferTimeService.java

- Closes #201 
이 부분의 캐시가 화면에 남아있지 않아서 여러 개의 겹치는 시간이 서버에 전송되는 경우를 막아주었습니다.
탭으로 시간을 선택하는 경우에만 발생할 수 있는 에러 같아서 같은 시작 시간대의 저장이 요청된 경우 예외를 던져주는 방식으로 진행했는데 임시방편같아서 썩 맘에 들지는 않네요..
-

#201 [fix] 회의 가능 시간 중복 입력 예외 처리

---

src/main/java/com/asap/server/service/PreferTimeService.java

- Closes #221 
1. 회의 생성 선호시간대 중복 입력 상황 해결
- 12:00 - 18:00 , 18:00 - 24:00 에서 18:00이 중복시간대로 입력이 되는 것을 확인 못했었네요! 고멘나사이..

#221 [fix] 회의 생성 선호시간대 중복 입력 상황 해결

---

src/main/java/com/asap/server/controller/dto/request/MeetingConfirmRequestDto.java
src/main/java/com/asap/server/controller/dto/request/UserRequestDto.java
src/main/java/com/asap/server/domain/Meeting.java
src/main/java/com/asap/server/domain/User.java
src/main/java/com/asap/server/service/MeetingService.java
src/test/java/com/asap/server/service/meeting/ConfirmMeetingMethodTest.java

- Closes #233
1. 내용
- 회의 확정 시 회의 시간 UPDATE 로직 수정
- `@Modifying(clearAutomatically = true)` 로 인해서 JPQL 실행 후 영속성 컨텍스트가 clear 되는데,
이 때 meeting 도 clear 가 되어서 더티 체킹으로 인한 UPDATE 가 안된 상태였습니다.
- 그래서 save 를 통해서 update 를 하는데, 이로 인해 meeting 을 다시 SELECT 한다는 건 좀 불편하지만...
더 나은 방법이 생각나지 않네요... 😭 
- 로직 수정 보다 테스트 코드 만드는 데 더 오래 걸렸네요... 😅

#233 [feat] 회의 확정 시 회의 시간 UPDATE 로직 수정

---

src/main/java/com/asap/server/common/aspect/LoggingAspect.java
src/main/java/com/asap/server/common/dto/ErrorDataResponse.java

- Closes #225 
1. 내용
- 로그 보는 데 너무 불편하더라고요... 그래서 포맷 살짝 수정했습니다.
- 또한 error data response 로그가 code, error 만 찍히고 있어서
toString 을 오버라이드 함으로써 data 까지 찍히도록 수정했습니다.
- lombok 의 toString 을 사용하면 error data reponse 내에 있는 data 만 로그에 찍히더라고요..

#225 [fix] 가독성을 위한 로그 포맷 수정

---

src/main/java/com/asap/server/service/UserService.java

- Closes #229 
1. 참여자 회의 가능 시간 중복 체크 했다고 생각했는데,, 방장만 되어있더라고요.. 테스트 코드 진짜 쓴다 진짜..
-

#229 [fix] 참여자 회의 가능 시간 중복 체크

---

src/main/java/com/asap/server/controller/UserController.java
src/main/java/com/asap/server/repository/AvailableDateRepository.java
src/main/java/com/asap/server/repository/MeetingRepository.java
src/main/java/com/asap/server/repository/PreferTimeRepository.java
src/main/java/com/asap/server/repository/TimeBlockRepository.java
src/main/java/com/asap/server/repository/TimeBlockUserRepository.java
src/main/java/com/asap/server/service/AvailableDateService.java
src/main/java/com/asap/server/service/MeetingService.java
src/main/java/com/asap/server/service/PreferTimeService.java
src/main/java/com/asap/server/service/TimeBlockService.java
src/main/java/com/asap/server/service/TimeBlockUserService.java
src/main/java/com/asap/server/service/UserService.java

- Closes #227 
**1. 로그인 시 발생하는 N+1 이슈**
지금까지 로그인을 했을 때 아래와 같은 플로우로 실행되었습니다.
```java
// 1. 회의 시간 조회
Meeting meeting = meetingRepository.findByIdWithHost(meetingId)
.orElseThrow(() -> new NotFoundException(Error.MEETING_NOT_FOUND_EXCEPTION));
// 2. 방장 조회
if (!meeting.checkHostName(requestDto.getName()))
throw new UnauthorizedException(Error.INVALID_HOST_ID_PASSWORD_EXCEPTION);
// 3. 시간을 입력했는지 조회
if (timeBlockUserService.isEmptyHostTimeBlock(meeting.getHost())) {
throw new HostTimeForbiddenException(Error.HOST_MEETING_TIME_NOT_PROVIDED, responseDto);
}
```
host 의 fetchType 이 LAZY이기 때문에 
`meeting.checkHostName(requestDto.getName())` 을 실행했을 때 SELECT 쿼리가 추가로 실행되기 때문에
N+1 이슈가 발생하고 있습니다.
그래서 fetch join 을 통해서 로그인 화면에서 회의를 불러올 때에는 host 정보까지 한번에 불어오도록 함으로써
N+1 이슈를 해결했습니다.
결과 : 3번의 쿼리 -> 2번의 쿼리
**2. …

#227 [feat] [feat] 로그인 시 발생하는 N+1 이슈 해결 및 기타 작업

---

src/main/java/com/asap/server/common/advice/ControllerExceptionAdvice.java

- Closes #150 
1. 예외 리턴 값 수정
- BadRequestException 잡아주는 핸들러 추가 후 주석이었던 코드들 모두 해제했습니다!

#150 [feat] 예외 리턴 값 수정

---

src/main/java/com/asap/server/common/advice/ControllerExceptionAdvice.java
src/main/java/com/asap/server/common/aspect/LoggingAspect.java
src/main/resources/file-error-appender.xml
src/main/resources/file-info-appender.xml

- Closes #242 
1. 내용
- appender 수정 및 info , error 로깅 분리
- 지금까지 error 내역은 error 파일에 error 를 일으켰던 요청의 헤더 값과 바디 값은 info 파일에 저장되었는데,
error 발생 시 error 파일 내에 body, header, 에러 값들이 같이 표시되면 에러를 확인하기 더 편할 것이라 생각해서 
info 레벨과 error 레벨을 분리했습니다.
- 하나의 파일로 로깅이 안되는 문제도 있고, 아래 사진과 같이 [공식 문서](https://logback.qos.ch/manual/appenders.html#SizeAndTimeBasedRollingPolicy)에서 비추천한다길래 file appender로 바꿨습니다.

#242 [feat] appender 수정 및 info , error 로깅 분리

---

build.gradle
src/main/java/com/asap/server/common/utils/BestMeetingUtil.java
src/main/java/com/asap/server/common/utils/strategy/impl/FindBestMeetingTimeStrategyImpl.java
src/main/java/com/asap/server/controller/dto/response/BestMeetingTimeResponseDto.java
src/main/java/com/asap/server/controller/dto/response/MeetingTimeResponseDto.java
src/main/java/com/asap/server/repository/TimeBlockUserRepository.java
src/main/java/com/asap/server/repository/timeblock/TimeBlockRepository.java
src/main/java/com/asap/server/repository/timeblock/TimeBlockRepositoryCustom.java
src/main/java/com/asap/server/repository/timeblock/TimeBlockRepositoryImpl.java
src/main/java/com/asap/server/repository/user/UserRepositoryCustom.java
src/main/java/com/asap/server/repository/user/UserRepositoryImpl.java
src/main/java/com/asap/server/service/AvailableDateService.java
src/main/java/com/asap/server/service/MeetingService.java
src/main/java/com/asap/server/service/TimeBlockService.java
src/main/java/com/asap/server/service/UserService.java
src/main/java/com/asap/server/service/vo/BestMeetingTimeVo.java
src/main/java/com/asap/server/service/vo/BestMeetingTimeWithUsersVo.java
src/main/java/com/asap/server/service/vo/TimeBlockVo.java
src/main/java/com/asap/server/service/vo/UserVo.java
src/test/java/com/asap/server/common/utils/GetBestMeetingTimeTest.java
src/test/java/com/asap/server/common/utils/strategy/FindBestMeetingTimeStrategyTest.java

- Closes #245 
1. 내용
- QueryDsl을 활용하여 최적의 회의 시간 알고리즘 수정
이전 알고리즘 방식에서는 쿼리가 아래와 같이 실행되었습니다.
- 회의 정보를 불러오는 SELECT 쿼리 1 번 실행
- 회의에 참여한 총 인원을 불러오는 SELECT 쿼리 1번 실행
- 총 AvailableDate 데이터를 불러오는 SELECT 쿼리 1번 실행
- 유저 N 명당 select 쿼리 N번 실행 (N ≥ 1)
- AvailableDate 데이터 M개 당 총 TimeBlock 데이터를 불러오는 SELECT 쿼리 M번 실행 (1≤ M ≤ 7)
- TimeBlock 데이터 K개 당 SELECT 쿼리 K번 실행 (1≤ K ≤ 259)
AvailableDate 당 37개의 TimeBlock이 생성될 수 있으므로 최악의 경우 37 * 7 = 259 개의 데이터가 생긴다.
그래서 최악의 경우 1 + 1 + 1 + N + 7 + 259 , 즉 N + 266 개의 쿼리가 실행됩니다.
---
쿼리 수를 줄이기 위해서 알고리즘 일부를 수정했습니다. 
- 알고리즘 내부에서 TimeBlock users를 사용하지 않고 users의 size만 필요하기 때문에 users를 구하기 위해 K번의 쿼리를 실행하지 않는 대신에 groupBy를 통해서 users의 size 값을 구한다.
- 최적, 차선의 회의 시간대를 3개 구한 후, 3개의 회의 시간대에 참여할 수 있는 users를 따로 구한다.
이러한 알고리즘 방식을 통해서 쿼리가 아래와 같이 개선되었습니다.
- 회의 정보를 불러오는 SELECT 쿼리 1 번 실행
- 회의에 참여한 …

#245 [feat] 최적의 회의 시간 알고리즘 QueryDsl로 마이그레이션

---

.github/workflows/dev-ci.yml
.github/workflows/prod-cd.yml
.github/workflows/prod-ci.yml
src/main/java/com/asap/server/common/utils/BestMeetingUtil.java
src/test/java/com/asap/server/common/utils/GetBestMeetingTimeTest.java
src/test/java/com/asap/server/repository/MeetingRepositoryCustomTest.java
src/test/java/com/asap/server/service/meeting/ConfirmMeetingMethodTest.java

- Closes #250 
1. 내용
-  최적의 회의 시간대의 가중치가 차선의 회의 시간대의 가중치 보다 낮을 때 발생하는 오류 해결
회의 시간이 30분이며, 회의 참여자가 3명일 때
(9:00 - 9:30 , 3명, 가중치 3) , (9:30 - 10:00 , 2명, 가중치 4), (10:30 - 11:00 , 2명, 가중치 4), (11:30 - 12:00 , 3명, 가중치 4) 
위 4가지 회의 시간이 있을 때,
(9:00 - 9:30 , 3명, 가중치 3) , (9:30 - 10:00 , 2명, 가중치 4), (10:30 - 11:00 , 2명, 가중치 4) 반환되어야 하지만
(9:30 - 10:00 , 2명, 가중치 4), (10:30 - 11:00 , 2명, 가중치 4), (11:30 - 12:00 , 3명, 가중치 4) 반환되고 있는 것을 파악했다.
회의 시간대의 가중치를 기준으로 정렬하는 로직을 수정하며 오류를 해결했다.

#250 [fix] 최적의 회의 시간대의 가중치가 차선의 회의 시간대의 가중치 보다 낮을 때 발생하는 오류 해결

---

src/main/java/com/asap/server/service/UserService.java

- Closes #256 
1. 내용
- 회의 시간이 1시간이고 최적의 시간이 22:00시 부터 1시간일 때 알고리즘에서 22:00 ~ 23:00를 반환합니다.
그래서 쿼리 문에 timeSlots in (22:00, 22:30, 23:00) 이 들어가게 됩니다.
하지만 22시부터 1시간의 정보는 22:00, 22:30 이기 때문에 23:00는 없어야 됩니다.
그래서 time slot 목록을 구할 때 end time ordinal을 1을 제거해서 timeslot 목록을 반환받습니다.

#256 [fix] 종료시각 ordinal에서 1 제거

---

.github/workflows/dev-ci.yml
.gitignore
build.gradle
src/main/java/com/asap/server/common/advice/ControllerExceptionAdvice.java
src/main/java/com/asap/server/common/aspect/LoggingAspect.java
src/main/java/com/asap/server/common/filter/CustomHttpServletRequestWrapper.java
src/main/java/com/asap/server/common/filter/CustomServletWrappingFilter.java
src/main/java/com/asap/server/common/interceptor/DuplicatedInterceptor.java
src/main/java/com/asap/server/config/WebConfig.java
src/main/java/com/asap/server/config/redis/RedisConfig.java
src/main/java/com/asap/server/controller/dto/request/MeetingSaveRequestDto.java
src/main/java/com/asap/server/controller/dto/request/PreferTimeSaveRequestDto.java
src/main/java/com/asap/server/exception/Error.java
src/main/java/com/asap/server/exception/model/InternalErrorException.java
src/main/java/com/asap/server/exception/model/TooManyRequestException.java
src/main/java/com/asap/server/service/MeetingService.java
src/main/java/com/asap/server/service/PreferTimeService.java
src/test/java/com/asap/server/concurrency/DuplicatedInterceptorTest.java
src/test/java/com/asap/server/service/meeting/ConfirmMeetingMethodTest.java

- Closes #259 
1. Wrapping Filter 변경
- 기존의 Wrapping ContentCachingWrapping 객체가 Request Wrapping이 잘 진행되지 않아서 커스텀 Wrapping 객체로 변경하였습니다!
2. Interceptor를 통해 중복된 요청 에러 처리
-  요청이 발생하면 Redis Hash Map에 IP와 RequestBody 값을 Key로 저장한 후 정삭적으로 실행되었을 때 postHandle 을 통해 Rmap에 담겨 있는 값을 삭제, 중간에 예외가 발생했을 때 afterCompletion에서 Rmap 내부의 값을 삭제
- 도중에 같은 요청이 들어온다면, Too Many Request 예외 발생
https://github.com/ASAP-as-soon-as-possible/ASAP_Server/blob/96556e8bc9b88327a5f7af949bf5754af95a8c45/src/main/java/com/asap/server/common/interceptor/DuplicatedInterceptor.java#L23-L27
- Interceptor를 사용하여 GlobalExceptionHandler가 해당 예외를 처리하고 반환할 수 있게 구현하였습니다.
- 처음엔 `@WebMvcTest` 를 통해 컨트롤러 테스트로 진행하려 했지만, 해당 테스트는 redis의 사용도 필요했기 때문에 인수 테스트가 적합하다고 생각해 `@SpringBootTest` 로 작성했습니다.
- `@SpringBootTest` 에는 MockMvc를 `@Autowired` 할 수 없기 때문에 …

#259 중복된 요청에 대한 에러 처리

---

src/main/java/com/asap/server/repository/user/UserRepositoryCustom.java
src/main/java/com/asap/server/repository/user/UserRepositoryImpl.java
src/main/java/com/asap/server/service/MeetingService.java
src/main/java/com/asap/server/service/UserService.java

- Closes #274 
1. 내용
다른 회의에서 동일한 date, 동일한 time_slot에 해당하는 유저의 정보까지 불러오는 이슈 발견
- query 내부에 meeting id를 추가해 특정 회의의 정보만 불러오도록 수정

#274 [hotfix] 회의 참여 인원 조회 쿼리 meeting id 조건 추가

---

.github/workflows/prod-cd.yml
Dockerfile
build.gradle
src/main/resources/file-error-appender.xml
src/main/resources/file-info-appender.xml

- Closes #277 
1. 내용
- Docker를 사용한 배포 방식이 메모리가 더 절약되는 것을 보고
- CD 방식을 Code Deploy에서 Docker로 수정했습니다.
- 아래와 같은 작업을 진행했습니다.
<details>
<summary>deploy.sh 정의</summary>
<div markdown="1">
```Shell
#!/bin/bash
docker_ps_output=$(sudo docker ps | grep $server_name)
echo "> ${docker_ps_output} docker_ps_output"
running_container_name=$(echo "$docker_ps_output" | awk '{print $NF}')
echo "> ${running_container_name} container_name"
blue_port=$(echo "$running_container_name" | awk -F'-' '{print $NF}')
echo "> ${blue_port} 블루포트"
if [ "$blue_port" = "8080" ]; then
green_port=8081
elif [ "$blue_port" = "8081" ]; then
green_port=8080
else
echo "> 실행 중인 port가 없습니다."
echo "> 8080을 할당합니다."
green_port=8080
fi
echo "> 도커 이미지 pull 받기"
docker pull ${docker_user_name}/${server_name}
echo "> ${green_port} 포트로 서버 …
```

#277 [feat] CD 방식 도커로 수정

---

src/main/java/com/asap/server/service/meeting/recommend/MeetingTimeRecommendService.java
src/main/java/com/asap/server/service/meeting/recommend/strategy/BestMeetingTimeStrategy.java
src/main/java/com/asap/server/service/meeting/recommend/strategy/impl/BestMeetingTimeStrategyImpl.java
src/test/java/com/asap/server/service/meeting/recommend/strategy/impl/BestMeetingTimeStrategyImplTest.java

- Closes #293 
1. 내용
- 해당 시간대의 회의 진행 시간만큼의 상단의 회의 시간을 반환하고, 만약 긴 시간대라면 하단의 회의 시간을 반환하는 구현체입니다.
- 수도 코드
```
bestMeetingTimes = emptyList()
for candidateMeetingTime: candidateMeetingTimes
[시작 시간 ~ 시작 시간 +duration]까지 BestMeetingTimeVo 생성 및 추가
if 긴 블록이라면 [마지막 시간 - duration ~ 끝 시간]까지 BestMeetingTimeVo 생성 및 추가
return bestMeetingTimes 
```
```
bestMeetingTimes = emptyList()
for candidateMeetingTime: candidateMeetingTimes
BestMeetingTimeVo <- startTime.index ~ startTime.index + duration
add(firstTime);
if endTime.index - startTime.index < duration 별 needBlock / 긴 블록이라면
BestMeetingTimeVo <-  endTime.index - duration ~ endTime.index
add(endTime);
return bestMeetingTimes 
```
- DisplayName 기입 방식을 이전과 다르게 간단하게 표현해봤습니다. 이전과 비교했을 때, 지금 방식이 더 가독성이 좋은지 궁금합니다.
이전
```
@DisplayName("회의 진행 시간이 2시간 30분 이상 3시간 …
```

#293 [feat] BestMeetingTimeStrategy 구현체 로직 개발

---

src/main/java/com/asap/server/service/meeting/recommend/MeetingTimeRecommendService.java

- Closes #302 
1. 내용
- 값 비교를 하도록 수정
제가 놓쳤던 부분이었습니다.
prod에 배포를 한 후 [07:00 ~ 15:00] 로 테스트를 했는데
[07:00~08:00 , 13:00 ~ 15:00 , null]이 반환을 기대했지만,
삭제가 잘 안되어 30분 시간이 반환되는 이슈를 발견했습니다.
단위 테스트는 잘 됐는데, 왜 안될까 끙끙 앓다가
값 비교가 아닌 객체 비교를 해서 이러한 현상이 발견됐다는 것을 알았고,
equals로 수정하여 값 비교를 하도록 수정했습니다.
> 단위 테스트는 잘 됐던 이유
given단에서 같은 available date 객체를 TimeBlockDto 내에 넣어줬기 때문에 단위 테스트가 잘 실행됐었습니다.. ㅎㅎ..

#302 [fix] local date 객체를 값 비교를 하도록 수정

---

src/main/java/com/asap/server/common/exception/model/HostTimeForbiddenException.java
src/main/java/com/asap/server/presentation/common/advice/ControllerExceptionAdvice.java
src/main/java/com/asap/server/presentation/controller/dto/request/HostLoginRequestDto.java
src/main/java/com/asap/server/presentation/controller/dto/response/HostLoginResponseDto.java
src/main/java/com/asap/server/presentation/controller/user/UserRegisterController.java
src/main/java/com/asap/server/service/UserService.java
src/main/java/com/asap/server/service/user/UserLoginService.java
src/test/java/com/asap/server/presentation/controller/user/UserRegisterControllerTest.java
src/test/java/com/asap/server/service/user/UserLoginServiceTest.java

- Closes #307 
1. 내용
- 모든 기능을 user service에 넣는 것이 아닌 하나의 서비스가 하나의 역할을 할 수 있도록 만들기 위해 별도의 로그인 서비스를 추가로 생성했습니다
- presentation 계층, service 계층 테스트 코드 추가했습니다.
- presentation 계층 테스트를 WebMvcTest를 사용해서 slice test를 하고 싶었는데, interceptor 등 추가로 넣어야 하는 bean들이 많아서 springboottest로 했습니다..

#307 [refactor] 로그인 기능 로그인 서비스로 분리

---

.github/workflows/dev-cd.yml

- Closes #311 
미루고 미뤘던 개발 서버, 구글 계정 하나 만들어서 배포했습니다.

#311 [feat] 개발 서버 cd 갱신

---

src/main/java/com/asap/server/service/time/UserMeetingScheduleService.java
src/test/java/com/asap/server/service/time/UserMeetingScheduleServiceTest.java

- Closes #326 
1. 내용
- 만약 사용자가 06:00 - 08:00 을 입력했다면, 실제 가능한 시간은 06:00, 06:30, 07:00, 07:30 입니다.
지금까지 08:00를 반환해서 오류가 생겼고, 이를 수정했습니다.
-

#326 [fix] 시간 별 유저 조회 로직 수정

---

build.gradle
src/main/java/com/asap/server/infra/slack/SlackUtil.java
src/main/java/com/asap/server/persistence/domain/time/UserMeetingSchedule.java

- Closes #328 
1. slack이 제공하는 의존성에서 보내는 사람을 지정하는 API가 deprecated 되고, slack 앱에서 지정하도록 변경됨에 따라 앱에서 지정 후 코드에서 제거하였습니다. 기존에 있던 주석들도 함께 지우고, String Builder 사용 방식도 수정하였습니다!
-

#328 [fix] slack util deprecated api 수정

---

src/main/java/com/asap/server/common/exception/Error.java
src/main/java/com/asap/server/common/exception/Success.java
src/main/java/com/asap/server/infra/slack/MetricsEvent.java
src/main/java/com/asap/server/infra/slack/MetricsSlackEventListener.java
src/main/java/com/asap/server/persistence/repository/internal/MetricsRepository.java
src/main/java/com/asap/server/presentation/config/async/AsyncConfig.java
src/main/java/com/asap/server/presentation/controller/internal/MetricsController.java
src/main/java/com/asap/server/presentation/controller/internal/docs/MetricsControllerDocs.java
src/main/java/com/asap/server/service/internal/MetricsService.java
src/test/java/com/asap/server/service/internal/MetricsServiceTest.java

- Closes #330 
1. 내용
- 명세대로 api 구현했습니다.
- api 응답 속도 감소와 서비스와 slack 서비스의 의존성을 줄이고자 스프링 이벤트 방식을 사용했습니다.
- 스프링 이벤트는 동기 방식으로 동작하기 때문에, 비동기 방식으로 동작하기 위해 `@Async` 어노테이션을 붙였고,
`@Async` 어노테이션은 호출할 때마다 스레드를 생성하기 때문에, 별도의 스레드 풀을 만들었습니다.
스레드 풀 같은 경우에는 이벤트 호출이 적을 것을 예상하여 스레드 풀을 1로 설정했습니다.

#330 [feat] 메트릭 api 구현

---

build.gradle
src/main/java/com/asap/server/persistence/repository/internal/MetricsRepository.java
src/main/java/com/asap/server/presentation/controller/internal/MetricsController.java
src/main/java/com/asap/server/presentation/controller/internal/docs/MetricsControllerDocs.java
src/main/java/com/asap/server/service/internal/MetricsService.java
src/test/java/com/asap/server/concurrency/DuplicatedInterceptorTest.java
src/test/java/com/asap/server/persistence/repository/internal/MetricsRepositoryGenerateDateFilterTest.java
src/test/java/com/asap/server/presentation/controller/MeetingRetrieveControllerTest.java
src/test/java/com/asap/server/service/internal/MetricsServiceTest.java

- Closes #332 
1. 내용
- 메트릭 API 요구사항 수정에 따라서 비즈니스 로직을 수정했습니다.
```
`/metrics` : 전체 데이터
`/metric?from=2024-08-01` : from 부터 현재까지 , created_at > from
`/metric?to=2024-08-01` :  to 까지 ,  created_at < to
`/metric?from=2024-08-04&to=2024-08-30` from에서 to까지 , from <= created_at <= to
```
위와 같이 요청해주시면 좋을 것 같습니다.
- Querydsl의 DateTimePath을 이용해서 분기처리를 통일했습니다. 만약 from, to가 null이라면 조건문이 자동으로 들어가지 않습니다.
- 커밋 따라서 작업 내용 보시면 리뷰하시기 편하실 것이라 생각합니다~!

#332 [feat] 메트릭 API 기간 입력 요구사항 반영
