ASAP-as-soon-as-possible/ASAP_Server

build.gradle, src/main/java/com/asap/server/config/swagger/SwaggerConfig.java, src/main/java/com/asap/server/controller/ServerProfileController.java
- Closes #7 
1. 내용
- swagger 초기 설정 했습니다.
- ec2 내에도 application.yaml 파일에 swagger 설정 추가했습니다.
- 노션 페이지에 application.yaml 파일에 추가 할 코드와 간략한 설명 추가해놓을게유~!
- 노션 server reference , db에 추가했어여~!
=> #7 [chore] swagger 초기 설정

src/main/java/com/asap/server/domain/DateAvailability.java, src/main/java/com/asap/server/domain/Meeting.java, src/main/java/com/asap/server/domain/MeetingTime.java, src/main/java/com/asap/server/domain/PreferTime.java, src/main/java/com/asap/server/domain/enums/Role.java
- Closes #16 
1. 내용
- entity 추가
- entity 추가
=> #16 [feat] entity 추가

README.md
=> #14 [docs] 리드미 작업

src/main/java/com/asap/server/config/WebConfig.java
- Closes #26 
1.  webConfig에 userIdResolver 추가
- 깜빡했네요..😓
=> #26 [fix] webConfig에 userIdResolver 추가

src/main/java/com/asap/server/domain/DateAvailability.java, src/main/java/com/asap/server/domain/Meeting.java, src/main/java/com/asap/server/domain/MeetingTime.java, src/main/java/com/asap/server/domain/enums/Duration.java, src/main/java/com/asap/server/domain/enums/Place.java, src/main/java/com/asap/server/domain/enums/TimeSlot.java
- Closes #20 
`LocalDateTime`, `LocalDate` 였던 필드를 `String month`, `String day`, `String dayOfWeek`, `String startTime`, `String endTime` 로 변경했습니다!
- 오탈자 없는지 확인 부탁드립니다!
=> #20 [fix] Entity column 변경 내역 수정

build.gradle, src/main/java/com/asap/server/config/jwt/JwtService.java, src/main/java/com/asap/server/controller/MeetingController.java, src/main/java/com/asap/server/controller/dto/request/MeetingSaveRequestDto.java, src/main/java/com/asap/server/controller/dto/request/PreferTimeSaveRequestDto.java, src/main/java/com/asap/server/controller/dto/response/MeetingSaveResponseDto.java, src/main/java/com/asap/server/domain/DateAvailability.java, src/main/java/com/asap/server/domain/Meeting.java, src/main/java/com/asap/server/domain/MeetingTime.java, src/main/java/com/asap/server/domain/PreferTime.java, src/main/java/com/asap/server/domain/User.java, src/main/java/com/asap/server/domain/enums/Duration.java, src/main/java/com/asap/server/domain/enums/Place.java, src/main/java/com/asap/server/domain/enums/Role.java, src/main/java/com/asap/server/domain/enums/TimeSlot.java, src/main/java/com/asap/server/exception/Error.java, src/main/java/com/asap/server/exception/Success.java, src/main/java/com/asap/server/repository/DateAvailabilityRepository.java, src/main/java/com/asap/server/repository/MeetingRepository.java, src/main/java/com/asap/server/repository/PreferTimeRepository.java, src/main/java/com/asap/server/repository/UserRepository.java, src/main/java/com/asap/server/service/MeetingService.java, src/main/java/com/asap/server/service/UserService.java
- Closes #28 
1. 회의 생성 API 작성
- Service에서 List를 받아와서 따로 저장 후 참조 후 연관관계 설정
- jwt Service 수정
3. enum 수정
- service 로직 최적화 하는 방법이 뭘지..🤔
=> [feat] 회의 생성 API 작성

src/main/java/com/asap/server/ServerApplication.java, src/main/java/com/asap/server/domain/AuditingTimeEntity.java, src/main/java/com/asap/server/domain/DateAvailability.java, src/main/java/com/asap/server/domain/Meeting.java, src/main/java/com/asap/server/domain/MeetingTime.java, src/main/java/com/asap/server/domain/PreferTime.java, src/main/java/com/asap/server/domain/User.java
- Closes #14 
1. 내용
- auditing time entity 구현 및 적용
- 세미나 내용 복붙입니다 ~ !
=> #14 [feat] auditing time entity 구현 및 적용

src/main/java/com/asap/server/controller/MeetingController.java, src/main/java/com/asap/server/controller/dto/response/AvailableDateResponseDto.java, src/main/java/com/asap/server/controller/dto/response/MeetingScheduleResponseDto.java, src/main/java/com/asap/server/controller/dto/response/PreferTimeResponseDto.java, src/main/java/com/asap/server/exception/Success.java, src/main/java/com/asap/server/service/MeetingService.java, src/main/java/com/asap/server/service/UserService.java
- Closes #34 
1. 선택지 제공 API 구현
- 비효율적인 코드 알려주시면 감사하겠습니다!
=> [feat] 선택지 제공 API 구현

src/main/java/com/asap/server/controller/MeetingController.java, src/main/java/com/asap/server/controller/dto/response/FixedMeetingResponseDto.java, src/main/java/com/asap/server/exception/Success.java, src/main/java/com/asap/server/service/MeetingService.java
- Closes #38 
1. 내용
- 큐카드 조회 api 구현
- 큐카드 조회 api 구현
=> #38 [feat] 큐카드 조회 api 구현

src/main/java/com/asap/server/common/advice/ControllerExceptionAdvice.java, src/main/java/com/asap/server/controller/MeetingController.java, src/main/java/com/asap/server/controller/dto/response/IsFixedMeetingResponseDto.java, src/main/java/com/asap/server/domain/Meeting.java, src/main/java/com/asap/server/exception/Error.java, src/main/java/com/asap/server/exception/Success.java, src/main/java/com/asap/server/exception/model/ConflictException.java, src/main/java/com/asap/server/service/MeetingService.java
- Closes #39 
1. [feat] 회의 유효성 확인 API
- Controller에서 리턴값없는 service 메소드 호출한 후 리턴하는데 이 과정이 맞는 걸까요?
=> [feat] 회의 유효성 확인 API

src/main/java/com/asap/server/controller/MeetingController.java, src/main/java/com/asap/server/controller/dto/response/AvailableDatesDto.java, src/main/java/com/asap/server/controller/dto/response/TimeSlotDto.java, src/main/java/com/asap/server/controller/dto/response/TimeTableResponseDto.java, src/main/java/com/asap/server/domain/enums/TimeSlot.java, src/main/java/com/asap/server/exception/Error.java, src/main/java/com/asap/server/exception/Success.java, src/main/java/com/asap/server/repository/MeetingTimeRepository.java, src/main/java/com/asap/server/service/MeetingService.java
- Closes #42 
종합 일정 시간표 API 구현
- service 단에서 리턴 로직 작성할 때 Map 안에 Map을 사용했는데 코드가 길어져서 검토 부탁드립니다.
=> #42 [feat] 종합 일정 시간표 API 구현

src/main/java/com/asap/server/common/advice/ControllerExceptionAdvice.java, src/main/java/com/asap/server/controller/UserController.java, src/main/java/com/asap/server/controller/dto/request/AvailableTimeRequestDto.java, src/main/java/com/asap/server/controller/dto/response/UserTimeResponseDto.java, src/main/java/com/asap/server/exception/Success.java, src/main/java/com/asap/server/service/UserService.java
- Closes #45 
1.  참여자 가능 시간 입력 API
- 중복 코드 없애기 실패....
=> [feat] 참여자 가능 시간 입력 API

src/main/java/com/asap/server/common/advice/ControllerExceptionAdvice.java, src/main/java/com/asap/server/domain/Meeting.java, src/main/java/com/asap/server/service/MeetingService.java, src/main/java/com/asap/server/service/UserService.java
- Closes #47 
1. Host 생성 User List에 추가 
- user list에 추가 및 validation exception adviser에 넣어줬습니다
=> [fix] Host 생성 User List에 추가 

src/main/java/com/asap/server/config/WebConfig.java, src/main/java/com/asap/server/config/resolver/meeting/MeetingIdResolver.java, src/main/java/com/asap/server/controller/MeetingController.java, src/main/java/com/asap/server/controller/ServerProfileController.java, src/main/java/com/asap/server/controller/UserController.java, src/main/java/com/asap/server/controller/dto/request/HostLoginRequestDto.java, src/main/java/com/asap/server/controller/dto/response/HostLoginResponseDto.java, src/main/java/com/asap/server/domain/DateAvailability.java, src/main/java/com/asap/server/domain/MeetingTime.java, src/main/java/com/asap/server/domain/PreferTime.java, src/main/java/com/asap/server/domain/User.java, src/main/java/com/asap/server/exception/Error.java, src/main/java/com/asap/server/exception/Success.java, src/main/java/com/asap/server/exception/model/ForbiddenException.java, src/main/java/com/asap/server/repository/UserRepository.java, src/main/java/com/asap/server/service/MeetingService.java, src/main/java/com/asap/server/service/UserService.java
- Closes #44 
1. 방장 정보 입력 API 구현
- 놓친 부분 있는지 확인 부탁
=> #44 [feat] 방장 정보 입력 API 구현

src/main/java/com/asap/server/controller/UserController.java, src/main/java/com/asap/server/exception/Error.java, src/main/java/com/asap/server/service/UserService.java
- Closes #51 
1. 회의 가능 시간 외 입력/ 중복 시간 입력 예외 처리 
- 중복 시간 확인은 Map 자료 구조 활용해서 날짜별 시간 중복되는 시간이 있는지  확인합니다!
- `DateAvailability` 에 저장되어있는 month, day가 `Integer.valueOf(String).toString()`값이라서 
`String userMeetingDate = Integer.valueOf(requestDto.getMonth()).toString() + Integer.valueOf(requestDto.getDay()).toString();` 이 값으로 contains 확인합니다!
=> [feat] 회의 가능 시간 외 입력/ 중복 시간 입력 예외 처리 

src/main/java/com/asap/server/controller/dto/response/AvailableDateResponseDto.java, src/main/java/com/asap/server/controller/dto/response/MeetingSaveResponseDto.java, src/main/java/com/asap/server/controller/dto/response/MeetingScheduleResponseDto.java, src/main/java/com/asap/server/controller/dto/response/PreferTimeResponseDto.java, src/main/java/com/asap/server/controller/dto/response/UserMeetingTimeResponseDto.java, src/main/java/com/asap/server/service/MeetingService.java, src/main/java/com/asap/server/service/UserService.java
=> #55 [refactor] 빌더 패턴 적용

src/main/java/com/asap/server/common/advice/ControllerExceptionAdvice.java, src/main/java/com/asap/server/config/WebConfig.java, src/main/java/com/asap/server/controller/MeetingController.java, src/main/java/com/asap/server/controller/dto/request/AvailableTimeRequestDto.java, src/main/java/com/asap/server/controller/dto/request/MeetingSaveRequestDto.java, src/main/java/com/asap/server/controller/dto/request/PreferTimeSaveRequestDto.java, src/main/java/com/asap/server/controller/dto/request/UserMeetingTimeSaveRequestDto.java, src/main/java/com/asap/server/domain/enums/Duration.java, src/main/java/com/asap/server/domain/enums/Place.java, src/main/java/com/asap/server/domain/enums/TimeSlot.java, src/main/java/com/asap/server/exception/Error.java, src/main/java/com/asap/server/service/MeetingService.java
- Closes #60 
1.  userId 유효성 검증 추가
-
=> #60 [feat] userId 유효성 검증 추가

src/main/java/com/asap/server/controller/dto/request/MeetingConfirmRequestDto.java, src/main/java/com/asap/server/controller/dto/request/UserMeetingTimeSaveRequestDto.java, src/main/java/com/asap/server/controller/dto/request/UserRequestDto.java, src/main/java/com/asap/server/domain/Meeting.java, src/main/java/com/asap/server/service/MeetingService.java, src/main/java/com/asap/server/service/UserService.java
- Closes #62 
1. 내용
- confirm request users 추가
- confirm request users 추가
=> #62 [feat] confirm request users 추가

src/main/java/com/asap/server/common/utils/BestMeetingUtil.java, src/main/java/com/asap/server/controller/MeetingController.java, src/main/java/com/asap/server/controller/UserController.java, src/main/java/com/asap/server/controller/dto/request/AvailableTimeRequestDto.java, src/main/java/com/asap/server/controller/dto/response/AvailableMeetingTimeDto.java, src/main/java/com/asap/server/controller/dto/response/BestMeetingTimeResponseDto.java, src/main/java/com/asap/server/controller/dto/response/DateAvailabilityDto.java, src/main/java/com/asap/server/controller/dto/response/MeetingDto.java, src/main/java/com/asap/server/controller/dto/response/MeetingTimeDto.java, src/main/java/com/asap/server/controller/dto/response/MeetingTimeResponseDto.java, src/main/java/com/asap/server/controller/dto/response/PossibleTimeCaseDto.java, src/main/java/com/asap/server/controller/dto/response/TimeSlotInfoDto.java, src/main/java/com/asap/server/controller/dto/response/UserDto.java, src/main/java/com/asap/server/domain/enums/Duration.java, src/main/java/com/asap/server/exception/Success.java, src/main/java/com/asap/server/service/MeetingService.java, src/main/java/com/asap/server/service/UserService.java, src/test/java/com/asap/server/common/utils/BestMeetingUtilTest.java
- Closes #66 
1. Valid 처리 & 저장 방식 변경
=> #66 [fix] Dto field 유효성 검증

src/main/java/com/asap/server/common/utils/BestMeetingUtil.java, src/main/java/com/asap/server/common/utils/TimeTableUtil.java, src/main/java/com/asap/server/domain/MeetingTime.java, src/main/java/com/asap/server/domain/User.java, src/main/java/com/asap/server/service/MeetingService.java, src/main/java/com/asap/server/service/vo/MeetingTimeVo.java
- Closes #73 
1. 종합 시간표 API hotfix
-
=> #73 [bugfix] 종합 시간표 API hotfix

src/main/java/com/asap/server/common/utils/BestMeetingUtil.java, src/main/java/com/asap/server/controller/MeetingController.java, src/main/java/com/asap/server/service/MeetingService.java, src/test/java/com/asap/server/common/utils/BestMeetingUtilTest.java
- Closes #72 
1. 내용
- 최적의 swagger 
- 최적의 swagger
=> #72 [chore] 최적의 swagger

src/main/java/com/asap/server/controller/MeetingController.java, src/main/java/com/asap/server/controller/UserController.java
- Closes #76 
1. swagger 기입 
-
=> #76 [chore] swagger 기입 

src/main/java/com/asap/server/service/MeetingService.java
=> #80 [fix] 파라미터 위치 수정

src/main/java/com/asap/server/controller/dto/response/MeetingTimeResponseDto.java, src/main/java/com/asap/server/domain/DateAvailability.java, src/main/java/com/asap/server/service/UserService.java
=> #82 [hotfix] 버그 fix

src/main/java/com/asap/server/common/utils/TimeTableUtil.java, src/main/java/com/asap/server/service/MeetingService.java
- Closes #87 
1. 종합 일정 시간표 bug fix
- 종합 일정 시간표 bug fix
=> #87 [hotfix] 종합 일정 시간표 bug fix

src/test/java/com/asap/server/common/utils/GetBestMeetingTimeTest.java
- Closes #71 
1. 내용
- 테스트 케이스 추가
-  테스트 케이스 추가
=> #71 [test] 테스트 케이스 추가

src/main/java/com/asap/server/common/utils/TimeTableUtil.java, src/main/java/com/asap/server/service/MeetingService.java
- Closes #89 
- 
1. [hotfix] 종합 일정 시간표 버그 fix
-
=> #89 [hotfix] 종합 일정 시간표 버그 fix

src/main/java/com/asap/server/ServerApplication.java, src/main/java/com/asap/server/common/advice/ControllerExceptionAdvice.java, src/main/java/com/asap/server/config/resolver/user/UserIdResolver.java, src/main/java/com/asap/server/exception/Error.java
- Closes #93 
1. 에러 견고하게 & 토큰 안넘어왔을 때 401에러
- 에러 견고하게 & 토큰 안넘어왔을 때 401에러
=> #93 [feat] 에러 견고하게 & 토큰 안넘어왔을 때 401에러

src/main/java/com/asap/server/service/MeetingService.java
- Closes #96 
1. [hotfix] 선택지 api bug fix
-
=> #96 [hotfix] 선택지 api bug fix

src/main/java/com/asap/server/common/advice/ControllerExceptionAdvice.java
- Closes #98 
1.  [Feat] Controller Adviser 처리
-
=> #98 [Feat] Controller Adviser 처리

src/main/java/com/asap/server/service/MeetingService.java
- Closes #100 
1. 시간 선택지 정렬 제공
- 시간 선택지 정렬 제공
=> #100 [fix] 시간 선택지 정렬 제공

src/main/java/com/asap/server/common/utils/TimeTableUtil.java
- Closes #102 
1.  이름 중복 에러 해결
-
=> #102 [fix] 이름 중복 에러 해결

src/main/java/com/asap/server/service/MeetingService.java
- Closes #104 
1. 내용
- 모든 유저에서 회의에 참석할 수 있는 유저로 수정
- 모든 유저에서 회의에 참석할 수 있는 유저로 수정
=> #104 [fix] 모든 유저에서 회의에 참석할 수 있는 유저로 수정

src/main/java/com/asap/server/controller/dto/request/MeetingSaveRequestDto.java, src/main/java/com/asap/server/controller/dto/request/PreferTimeSaveRequestDto.java, src/main/java/com/asap/server/domain/AvailableDate.java, src/main/java/com/asap/server/domain/Meeting.java, src/main/java/com/asap/server/domain/TimeBlock.java, src/main/java/com/asap/server/repository/AvailableDateRepository.java, src/main/java/com/asap/server/repository/DateAvailabilityRepository.java, src/main/java/com/asap/server/repository/MeetingTimeRepository.java, src/main/java/com/asap/server/service/MeetingService.java, src/test/java/com/asap/server/controller/MeetingControllerTest.java, src/test/java/com/asap/server/service/MeetingControllerTest.java
- Closes #118 
1.  회의 유효성 검사 API 수정
- #118 태그만 보면 될 것 같습니다!
=> #118 [fix] 회의 유효성 검사 API 수정

src/main/java/com/asap/server/domain/AvailableDate.java, src/main/java/com/asap/server/service/AvailableDateService.java, src/main/java/com/asap/server/service/MeetingService.java, src/main/java/com/asap/server/service/PreferTimeService.java
- Closes #110 
1. 회의 생성 API 수정
- MeetingService 람다식에서 `s -> new AvailableDate(LocalDate.parse(s.substring(0, 10), formatter))` 이 부분을 `newInstance`같은 static 함수로 빼지 않고 인자를 parsing 해줘야 해서 생성자 사용했습니다! builder 사용하는게 나을지 고민 중..
=> #110 [fix] 회의 생성 API 수정

src/main/java/com/asap/server/controller/dto/request/MeetingSaveRequestDto.java, src/main/java/com/asap/server/controller/dto/response/MeetingScheduleResponseDto.java, src/main/java/com/asap/server/domain/AvailableDate.java, src/main/java/com/asap/server/domain/ConfirmedDateTime.java, src/main/java/com/asap/server/domain/Meeting.java, src/main/java/com/asap/server/domain/MeetingV2.java, src/main/java/com/asap/server/domain/Place.java, src/main/java/com/asap/server/domain/PreferTimeV2.java, src/main/java/com/asap/server/domain/TimeBlock.java, src/main/java/com/asap/server/domain/TimeBlockUser.java, src/main/java/com/asap/server/domain/UserV2.java, src/main/java/com/asap/server/domain/enums/PlaceType.java, src/main/java/com/asap/server/service/MeetingService.java
- Closes #536
1. 내용
- entity table 불일치 에러 해결
- 로컬 관리 잘하겠습니다
=> [hotfix] entity table 불일치 에러 해결

build.gradle, src/main/java/com/asap/server/controller/UserController.java, src/main/java/com/asap/server/domain/AvailableDate.java, src/main/java/com/asap/server/domain/MeetingV2.java, src/main/java/com/asap/server/domain/PreferTimeV2.java, src/main/java/com/asap/server/domain/TimeBlockUser.java, src/main/java/com/asap/server/domain/UserV2.java, src/main/java/com/asap/server/repository/MeetingV2Repository.java, src/main/java/com/asap/server/repository/TimeBlockUserRepository.java, src/main/java/com/asap/server/service/UserService.java
- Closes #124 
1. 내용
- 방장 로그인 API 구현했습니더
-
=> #124 [feat] 방장 로그인 API 구현

src/main/java/com/asap/server/common/utils/DateUtil.java, src/main/java/com/asap/server/controller/MeetingController.java, src/main/java/com/asap/server/domain/Place.java, src/main/java/com/asap/server/exception/Error.java, src/main/java/com/asap/server/repository/AvailableDateRepository.java, src/main/java/com/asap/server/repository/PreferTimeV2Repository.java, src/main/java/com/asap/server/service/AvailableDateService.java, src/main/java/com/asap/server/service/MeetingService.java, src/main/java/com/asap/server/service/PreferTimeService.java
- Closes #135 
1. 선택지 제공 API 수정
함수명이 맘에 안들어요,, 선착순으로 추천받아요
=> #135 [feat] 선택지 제공 API 수정

src/main/java/com/asap/server/controller/MeetingController.java, src/main/java/com/asap/server/domain/MeetingV2.java, src/main/java/com/asap/server/service/MeetingService.java
- Closes #133 
1. 내용
- 확정된 회의 확인 API 수정
-
=> #133 [fix] 확정된 회의 확인 API 수정

src/main/java/com/asap/server/common/utils/DateUtil.java, src/main/java/com/asap/server/controller/MeetingController.java, src/main/java/com/asap/server/domain/ConfirmedDateTime.java, src/main/java/com/asap/server/domain/Place.java, src/main/java/com/asap/server/repository/UserV2Repository.java, src/main/java/com/asap/server/service/MeetingService.java, src/main/java/com/asap/server/service/UserV2Service.java
- Closes #132 
1. 내용
- 확정된 큐카드 불러오는 api 구현
-
=> #132 [fix] 확정된 큐카드 불러오는 api 구현

src/main/java/com/asap/server/service/MeetingService.java, src/main/java/com/asap/server/service/UserV2Service.java
- Closes #139 
1. 유저 생성 로직 수정
-
=> #139 [fix] 유저 생성 로직 수정

src/main/java/com/asap/server/common/utils/DateUtil.java, src/main/java/com/asap/server/domain/ConfirmedDateTime.java, src/main/java/com/asap/server/domain/MeetingV2.java, src/main/java/com/asap/server/domain/UserV2.java, src/main/java/com/asap/server/repository/UserV2Repository.java, src/main/java/com/asap/server/service/MeetingService.java, src/main/java/com/asap/server/service/UserV2Service.java
- Closes #112 
1. 내용
- 시간 확정 API 구현
-
=> #112 [fix] 시간 확정 API 구현

src/main/java/com/asap/server/controller/UserController.java, src/main/java/com/asap/server/service/UserV2Service.java
- Closes #114 
1. 사용자 가능 시간 입력 로직 수정
-
=> #114 [feat] 사용자 가능 시간 입력 로직 수정

.github/workflows/dev-cd.yml
- Closes #146 
1. 개발 서버용 워크플로우 파일 작성
-
=> #146 [docs] 개발 서버용 워크플로우 파일 작성

src/main/java/com/asap/server/controller/MeetingController.java, src/main/java/com/asap/server/service/TimeBlockUserService.java, src/main/java/com/asap/server/service/UserService.java
=> #154 [feat] 서비스로 로직 이동

src/main/java/com/asap/server/common/utils/BestMeetingUtil.java, src/main/java/com/asap/server/service/vo/BestMeetingTimeVo.java, src/test/java/com/asap/server/common/utils/GetBestMeetingTimeTest.java, src/test/java/com/asap/server/common/utils/SearchBestMeetingTest.java
- Closes #158 
1. 내용
- 최적의 회의시간 가중치 반영
- 최적의 회의시간 가중치 반영
=> #158 [feat] 최적의 회의시간 가중치 반영

src/main/java/com/asap/server/controller/dto/response/MeetingScheduleResponseDto.java
=> #164 [fix] 와일드카드 삭제

src/main/java/com/asap/server/controller/MeetingController.java, src/main/java/com/asap/server/controller/UserController.java, src/main/java/com/asap/server/exception/Error.java, src/main/java/com/asap/server/service/MeetingService.java, src/main/java/com/asap/server/service/UserService.java
- Closes #166 
1. 방장 가능시간 입력 예외 추가
2. 
-
=> #166 [fix] 방장 가능시간 입력 예외 추가

src/main/java/com/asap/server/service/AvailableDateService.java, src/main/java/com/asap/server/service/PreferTimeService.java
- Closes #174 
1. 선택지 제공 API 시간 정렬
-
=> #174 [hotfix] 선택지 제공 API 시간 정렬

src/main/java/com/asap/server/common/advice/ControllerExceptionAdvice.java, src/main/java/com/asap/server/exception/Error.java
- Closes #179 
1. 내용
-  지원하지 않는 메서드 호출 시 405 반환
=> #179 [feat] 지원하지 않는 메서드 호출 시 405 반환

src/main/java/com/asap/server/domain/Meeting.java, src/main/java/com/asap/server/service/UserService.java
- Closes #187
- 로그인 로직 보완
1. 내용
- 설명
-
=> #187 [hotfix] 로그인 로직 보완

src/main/java/com/asap/server/domain/Meeting.java, src/main/java/com/asap/server/service/UserService.java
- Closes #187 
1. 내용
- hotfix 변경점 develop 반영
-
=> #187 [hotfix] hotfix 변경점 develop 반영

README.md
=> #190 [docs] 리드미 수정

src/main/java/com/asap/server/common/utils/DateUtil.java, src/main/java/com/asap/server/service/MeetingService.java
- Closes #202 
1. 24:00 -> 00:00 parse 처리
-
=> #202 [hotfix] 24:00 -> 00:00 parse 처리

src/main/java/com/asap/server/controller/MeetingController.java, src/main/java/com/asap/server/controller/UserController.java, src/main/java/com/asap/server/service/MeetingService.java, src/main/java/com/asap/server/service/UserService.java
- Closes #232 
1. 내용
- 확정된 회의를 로그인 시 409 에러 반환
- 확정된 회의를 로그인 시 409 에러 반환
=> #232 [feat] 확정된 회의를 로그인 시 409 에러 반환

src/main/java/com/asap/server/common/utils/DateUtil.java
- Closes #253 
1. 내용
- 2023으로 고정되어 있는 시간을 2024로 수정했습니다.
=> #253 [fix] 2023 -> 2024로 수정

src/main/java/com/asap/server/common/advice/ControllerExceptionAdvice.java, src/main/java/com/asap/server/controller/dto/request/MeetingSaveRequestDto.java, src/main/java/com/asap/server/controller/dto/request/UserMeetingTimeSaveRequestDto.java, src/main/java/com/asap/server/exception/Error.java, src/main/java/com/asap/server/service/AvailableDateService.java, src/main/java/com/asap/server/service/UserService.java
- Closes #264 
1. 내용
- [방장, 유저 시간 생성 시 available date 생성 로직 수정](0008dbb3bc322ee48c1d4b37990a2febb02f4ae6)
- [회의 생성 시 available date 생성 로직 수정](b3c20c4aa36ce1c6223e283ca454e20f0b1abcd6)
위 커밋 메시지에 해당 작업 작성했습니다.
커밋 메시지 보면서 pr 확인해주세요~!
=> #264 [fix] 회의 시간 등록 관련 로직 수정

README.md
- Closes #283 
Read me 수정했습니다.
수정하고 싶은 부분 있으면 남겨주세요!
asap 소개 부분에서 굵은 글씨 관련해서 임의로 작성해봤는데,
왜 강조했지 싶은 부분이라든지, 강조하고 싶은 부분 리뷰 남겨주세요!
=> #283 [docs] read me 수정

src/test/java/com/asap/server/persistence/repository/user/UserRepositoryImplTest.java
- Closes #285 
1. 내용
- 회의 참여 인원 칼럼 변경 쿼리 테스트 코드 작성
- 테스트 커버리지를 높이기 챌린지 1일차입니다. 작심삼일 안되도록 노력해보겠습니다.
=> #285 [test] 회의 참여 인원 칼럼 변경 쿼리 테스트 코드 작성

src/main/java/com/asap/server/common/exception/Error.java, src/main/java/com/asap/server/presentation/common/advice/ControllerExceptionAdvice.java
- Closes #265 
1. 내용
- 에러 메시지를 로깅하려 했는데, 에러 메시지가 불친절해서 기본으로 로깅되는 request header, body 값으로 분석하면 될 것 같습니다..
=> #265 [feat] IllegalArgumentException 에러 수집

src/main/java/com/asap/server/common/exception/Error.java
- Closes #314 
1. 내용
- 알럿을 위한 에러 메시지 수정했습니다.
=> #314 [fix] 알럿을 위한 에러 메시지 수정

src/main/java/com/asap/server/common/utils/DateUtil.java
- Closes #335 
1. 내용
- 새해가 밝았습니다. 하드코딩 된 2024를 2025로 수정했습니다..
레거시 없애고 싶네요.. ㅠㅠ
-
=> #335 [fix] 2024 -> 2025로 수정
